In [3]:
import numpy as np
arr = np.ones((3, 4))

In [4]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [5]:
arr + 5

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [6]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [15]:
np.empty((3, 4))

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [22]:
np.eye(3, dtype = int) #n*n matrix #tO calculate inverse of matroix

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [23]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
#optional

import pandas as pd
pd.DataFrame(arr)

,0,1,2,3
0,1.0,1.0,1.0,1.0
1,1.0,1.0,1.0,1.0
2,1.0,1.0,1.0,1.0


In [43]:
#extra topics
import random
random.choice((1, 2, 3, 4, 5, 6))

random.choice('Ajay')
random.randrange(1, 10)
random.random() # a random no is generated between o (included), 1 will be excluded

lis = [1, 2, 3, 4, 5]
random.shuffle(lis)

random.uniform(7, 14) #a no between 7 and 14

'j'

In [ ]:
np.array([])

In [287]:
np.random.random_sample()

0.9211111156563901

In [279]:
type(np.random.random_sample())

float

In [280]:
np.random.random_sample((5,))

array([0.90202035, 0.60630875, 0.15373777, 0.86313403, 0.42078372])

In [47]:
np.random.rand(1)

array([0.11447432])

In [44]:
np.random.rand(2, 3)

array([[0.36447448, 0.62336784, 0.83770828],
       [0.96798408, 0.50156134, 0.91970993]])

In [49]:
np.random.randn(2, 3)

array([[ 0.6934026 , -0.40988039, -0.29346066],
       [ 0.00731871,  1.51932967, -0.41561844]])

In [50]:
np.random.random_sample()

0.13122192085217144

In [51]:
np.random.randint(1, 5, size = (3, 4))

array([[1, 2, 3, 3],
       [2, 4, 1, 4],
       [1, 4, 4, 4]])

In [52]:
arr = np.random.randint(1, 5, size = (3, 4))

In [53]:
arr

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [54]:
arr.size

12

In [55]:
arr.shape

(3, 4)

In [56]:
arr.ndim

2

In [57]:
arr

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [60]:
arr.reshape(2, 6) #array size can not change, multiples of array size

array([[4, 1, 1, 2, 3, 2],
       [3, 4, 4, 1, 3, 1]])

In [61]:
arr.reshape(6, 2)

array([[4, 1],
       [1, 2],
       [3, 2],
       [3, 4],
       [4, 1],
       [3, 1]])

In [64]:
arr.reshape(12,)

array([4, 1, 1, 2, 3, 2, 3, 4, 4, 1, 3, 1])

In [65]:
arr.reshape(12, 1)

array([[4],
       [1],
       [1],
       [2],
       [3],
       [2],
       [3],
       [4],
       [4],
       [1],
       [3],
       [1]])

In [66]:
arr.reshape(12,2)

ValueError: cannot reshape array of size 12 into shape (12,2)

In [67]:
arr.reshape(4, 3)

array([[4, 1, 1],
       [2, 3, 2],
       [3, 4, 4],
       [1, 3, 1]])

In [68]:
arr.reshape(3,4)

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [69]:
arr

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [73]:
arr.reshape(4, -1)

array([[4, 1, 1],
       [2, 3, 2],
       [3, 4, 4],
       [1, 3, 1]])

In [74]:
arr.reshape(4, -100)

array([[4, 1, 1],
       [2, 3, 2],
       [3, 4, 4],
       [1, 3, 1]])

In [75]:
arr.reshape(3, -100)

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [81]:
arr.reshape(-1, 4)

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [87]:
arr

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [89]:
arr.reshape(12, ).base

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [90]:
arr

array([[4, 1, 1, 2],
       [3, 2, 3, 4],
       [4, 1, 3, 1]])

In [91]:
arr.size

12

In [92]:
arr.reshape(2, 2, 3)

array([[[4, 1, 1],
        [2, 3, 2]],

       [[3, 4, 4],
        [1, 3, 1]]])

In [93]:
arr.reshape(1, 2, 2, 3)

array([[[[4, 1, 1],
         [2, 3, 2]],

        [[3, 4, 4],
         [1, 3, 1]]]])

In [94]:
arr.reshape(4, 3, 1)

array([[[4],
        [1],
        [1]],

       [[2],
        [3],
        [2]],

       [[3],
        [4],
        [4]],

       [[1],
        [3],
        [1]]])

In [96]:
arr.reshape(1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3)

array([[[[[[[[[[[[4, 1, 1],
                 [2, 3, 2]],

                [[3, 4, 4],
                 [1, 3, 1]]]]]]]]]]]])

In [98]:
lis = [1, 2, 3, 4]
arr = np.array(lis)

In [99]:
arr

array([1, 2, 3, 4])

In [100]:
arr.ndim

1

In [102]:
arr2 = np.array([[2, 3], [4, 5]])
arr2

array([[2, 3],
       [4, 5]])

In [103]:
arr2.ndim

2

In [105]:
arr2 = np.zeros((3, 4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [106]:
arr2.ndim

2

In [107]:
arr3 = np.zeros((1, 3, 4)) # 3 rows, 4 columns >> 2d array + 1d
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [108]:
arr3.ndim

3

In [109]:
arr3.shape

(1, 3, 4)

In [110]:
arr4 = np.zeros((1, 1, 3, 4)) # 3 rows, 4 columns >> 2d array + 1d +1d
arr4

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [111]:
arr4.ndim

4

In [112]:
arr4.shape

(1, 1, 3, 4)

In [120]:
arr3 = np.zeros((3, 3, 4))
arr3

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [117]:
arr3.ndim

3

In [121]:
arr3.shape

(3, 3, 4)

In [257]:
arr1 = np.random.randint(1, 10, (5, 6))

In [258]:
arr1

array([[2, 7, 4, 4, 8, 3],
       [6, 4, 8, 4, 4, 2],
       [3, 7, 5, 7, 2, 3],
       [7, 4, 3, 5, 6, 8],
       [5, 9, 4, 8, 4, 4]])

In [259]:
arr1 > 5

array([[False,  True, False, False,  True, False],
       [ True, False,  True, False, False, False],
       [False,  True, False,  True, False, False],
       [ True, False, False, False,  True,  True],
       [False,  True, False,  True, False, False]])

In [260]:
arr1[arr1 > 5]

array([7, 8, 6, 8, 7, 7, 7, 6, 8, 9, 8])

In [261]:
arr1[arr1 < 5]

array([2, 4, 4, 3, 4, 4, 4, 2, 3, 2, 3, 4, 3, 4, 4, 4])

In [262]:
arr1

array([[2, 7, 4, 4, 8, 3],
       [6, 4, 8, 4, 4, 2],
       [3, 7, 5, 7, 2, 3],
       [7, 4, 3, 5, 6, 8],
       [5, 9, 4, 8, 4, 4]])

In [265]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [266]:
arr[0]

array([0., 0., 0., 0.])

In [268]:
arr[0]

array([0., 0., 0., 0.])

In [269]:
arr1

array([[2, 7, 4, 4, 8, 3],
       [6, 4, 8, 4, 4, 2],
       [3, 7, 5, 7, 2, 3],
       [7, 4, 3, 5, 6, 8],
       [5, 9, 4, 8, 4, 4]])

In [276]:
arr1[0:2, [0,2]] #0th - 1st row in continuation and 0th and 2nd column

array([[2, 4],
       [6, 8]])

In [277]:
#slicing on both rows and column
arr1[0:2, 1:3]

array([[7, 4],
       [4, 8]])

In [272]:
arr1[0:2, [0, 1]]

array([[2, 7],
       [6, 4]])

In [ ]:
arr

In [145]:
arr1[0, [1,3]]

array([7, 1])

In [154]:
arr1[2:4, [0, 2]]

array([[2, 4],
       [2, 9]])

In [156]:
arr1

array([[3, 7, 7, 1, 5, 2],
       [6, 1, 5, 6, 6, 8],
       [2, 8, 4, 2, 9, 3],
       [2, 1, 9, 5, 8, 7],
       [6, 2, 7, 6, 6, 1]])

In [160]:
arr1[2:5]

array([[2, 8, 4, 2, 9, 3],
       [2, 1, 9, 5, 8, 7],
       [6, 2, 7, 6, 6, 1]])

In [164]:
arr1[2:5, 0:2] #slicing

array([[2, 8],
       [2, 1],
       [6, 2]])

In [167]:
arr1[2:5, [0, 2]]

array([[2, 4],
       [2, 9],
       [6, 7]])

In [170]:
arr1[[2,4]]

array([[2, 8, 4, 2, 9, 3],
       [6, 2, 7, 6, 6, 1]])

In [171]:
arr1

array([[3, 7, 7, 1, 5, 2],
       [6, 1, 5, 6, 6, 8],
       [2, 8, 4, 2, 9, 3],
       [2, 1, 9, 5, 8, 7],
       [6, 2, 7, 6, 6, 1]])

In [172]:
arr1

array([[3, 7, 7, 1, 5, 2],
       [6, 1, 5, 6, 6, 8],
       [2, 8, 4, 2, 9, 3],
       [2, 1, 9, 5, 8, 7],
       [6, 2, 7, 6, 6, 1]])

In [175]:
arr1[[2, 4]] #selecting specific column

array([[2, 8, 4, 2, 9, 3],
       [6, 2, 7, 6, 6, 1]])

In [177]:
arr1[2 : 4] #slicing

array([[2, 8, 4, 2, 9, 3],
       [2, 1, 9, 5, 8, 7]])

In [179]:
arr1

array([[3, 7, 7, 1, 5, 2],
       [6, 1, 5, 6, 6, 8],
       [2, 8, 4, 2, 9, 3],
       [2, 1, 9, 5, 8, 7],
       [6, 2, 7, 6, 6, 1]])

In [182]:
arr1[2:4, [1, 3]]

array([[8, 2],
       [1, 5]])

In [183]:
arr1 = np.random.randint(1, 3, (3,3))
arr2 = np.random.randint(1, 3, (3,3))

In [184]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

## 

In [185]:
arr2

array([[2, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [186]:
arr1 + arr2

array([[3, 3, 3],
       [3, 3, 2],
       [4, 2, 3]])

In [187]:
arr1 - arr2

array([[-1,  1,  1],
       [ 1,  1,  0],
       [ 0,  0, -1]])

In [188]:
arr1 * arr2

array([[2, 2, 2],
       [2, 2, 1],
       [4, 1, 2]])

In [189]:
#matrix multiplication


arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [190]:
arr2

array([[2, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [191]:
arr1 @ arr2

array([[8, 5, 7],
       [8, 5, 6],
       [7, 4, 5]])

In [192]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [193]:
arr2

array([[2, 1, 1],
       [1, 1, 1],
       [2, 1, 2]])

In [194]:
arr1 / arr2 #index wise divison

array([[0.5, 2. , 2. ],
       [2. , 2. , 1. ],
       [1. , 1. , 0.5]])

In [196]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [197]:
arr1 / 0

C:\Users\ajayk\AppData\Local\Temp\ipykernel_12284\824215542.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1 / 0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [ ]:
#Broad casting

In [198]:
arr = np.zeros((3, 4))

In [199]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [200]:
arr + 5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [253]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [254]:
a = np.array([1, 2, 3, 4])

In [255]:
a.shape

(4,)

In [256]:
a

array([1, 2, 3, 4])

In [204]:
arr + a 

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [207]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [208]:
a

array([1, 2, 3])

In [205]:
a = np.array([1, 2, 3])

In [210]:
a = np.array([[1, 2, 3]])

In [212]:
a.T

array([[1],
       [2],
       [3]])

In [214]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [215]:
a

array([[1, 2, 3]])

In [216]:
arr + a.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [217]:
a.T

array([[1],
       [2],
       [3]])

In [218]:
a = np.array([1, 2, 3])
a.T

array([1, 2, 3])

In [219]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [220]:
np.sqrt(arr1)

array([[1.        , 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.        ],
       [1.41421356, 1.        , 1.        ]])

In [221]:
np.log10(arr1)

array([[0.     , 0.30103, 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.30103, 0.     , 0.     ]])

In [222]:
np.exp(arr1)

array([[2.71828183, 7.3890561 , 7.3890561 ],
       [7.3890561 , 7.3890561 , 2.71828183],
       [7.3890561 , 2.71828183, 2.71828183]])

In [225]:
a

array([1, 2, 3])

In [224]:
np.min(a)

1

In [226]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [227]:
np.min(arr1)

1

In [228]:
np.max(arr1)

2

In [229]:
arr1

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [230]:
arr1.T

array([[1, 2, 2],
       [2, 2, 1],
       [2, 1, 1]])

In [231]:
arr1.flatten() #reduce higher dimension to 1 d

array([1, 2, 2, 2, 2, 1, 2, 1, 1])

In [ ]:
#expand_dims >>  expands the array by inserting a new axis

In [235]:
arr = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])

In [236]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3]])

In [237]:
np.sum(arr)

27

In [238]:
np.sum(arr, axis = 0)

array([ 6,  9, 12])

In [239]:
np.sum(arr, axis = 1)

array([ 6, 15,  6])

In [240]:
#expand_dims >>expand the dimension of array
arr = np.array([1, 2, 3, 4])
arr

array([1, 2, 3, 4])

In [241]:
arr.ndim

1

In [242]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[1, 2, 3, 4]])

In [243]:
arr1.ndim

2

In [244]:
arr2 = np.expand_dims(arr1, axis = 0)
arr2

array([[[1, 2, 3, 4]]])

In [245]:
arr2.shape

(1, 1, 4)

In [246]:
arr

array([1, 2, 3, 4])

In [247]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[1],
       [2],
       [3],
       [4]])

In [248]:
arr = np.zeros((3, 4))

In [249]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [251]:
arr1 = np.expand_dims(arr, axis = 1)
arr1

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [252]:
arr1 = np.expand_dims(arr, axis = 0)
arr1

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])